services:
  - type: web
    name: cms-api
    env: dotnet
    region: oregon
    plan: free
    branch: master  # or Solomon/v2 if that's your working branch
    rootDir: backend/MyApp.API
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/MyApp.API.dll
    publishPath: out
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
